### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cbeach47** [smoghal/cognito-amplify-idp-auth#3]
Hello @smoghal ! Thanks for putting this guide together.  I've been looking for something that helps tie these concepts together. I did not see a license attached to the guide or to the code. Would you be willing to assign a license to the project or provide some other written release that lets folks create derivative work / use the code in projects?

**Comment by smoghal** [comment]
Done.  If licensing terms change in future, I will update this appropriately.
Thanks for bringing this up.
